#!/usr/bin/bash

BIN_DIR="../bin/examples"
SRC=$1
BINARY="../bin/examples/$(basename $SRC .c)"

shift 1
ARGS="$@"

mkdir -p $BIN_DIR

gcc $SRC "../soya/glad/glad.c" \
    $ARGS \
    -DRESOURCE_DIR=\"$(realpath ../resources)\" \
    -I../ -std=c11 -lm -lglfw \
    -o $BINARY

$BINARY
