#!/usr/bin/bash

mkdir -p ../bin/examples

binary=$(basename $(ls *$1*) .c)

shift 1

args="$@"

gcc "$binary.c" \
    $args \
    -g \
    -std=c11 \
    -lm -lglfw -lepoxy -lpng \
    -Wall -Wpedantic -Wextra \
    -o "../bin/examples/$binary"

../bin/examples/$binary
