#ifndef _SOYA_DEFAULTS_H
#define _SOYA_DEFAULTS_H

#define SY_DEFAULT_GL_VERSION_MAJOR 4
#define SY_DEFAULT_GL_VERSION_MINOR 3
#define SY_DEFAULT_WINDOW_WIDTH 1280
#define SY_DEFAULT_WINDOW_HEIGHT 720
#define SY_DEFAULT_WINDOW_SAMPLES 8

#endif  // _SOYA_DEFAULT_H
